// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: telemetry.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_telemetry_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_telemetry_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_telemetry_2eproto;
namespace rov {
namespace telemetry {
class JoystickCommand;
struct JoystickCommandDefaultTypeInternal;
extern JoystickCommandDefaultTypeInternal _JoystickCommand_default_instance_;
class SensorData;
struct SensorDataDefaultTypeInternal;
extern SensorDataDefaultTypeInternal _SensorData_default_instance_;
class Vector3D;
struct Vector3DDefaultTypeInternal;
extern Vector3DDefaultTypeInternal _Vector3D_default_instance_;
class test;
struct testDefaultTypeInternal;
extern testDefaultTypeInternal _test_default_instance_;
}  // namespace telemetry
}  // namespace rov
PROTOBUF_NAMESPACE_OPEN
template<> ::rov::telemetry::JoystickCommand* Arena::CreateMaybeMessage<::rov::telemetry::JoystickCommand>(Arena*);
template<> ::rov::telemetry::SensorData* Arena::CreateMaybeMessage<::rov::telemetry::SensorData>(Arena*);
template<> ::rov::telemetry::Vector3D* Arena::CreateMaybeMessage<::rov::telemetry::Vector3D>(Arena*);
template<> ::rov::telemetry::test* Arena::CreateMaybeMessage<::rov::telemetry::test>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace rov {
namespace telemetry {

// ===================================================================

class Vector3D final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rov.telemetry.Vector3D) */ {
 public:
  inline Vector3D() : Vector3D(nullptr) {}
  ~Vector3D() override;
  explicit PROTOBUF_CONSTEXPR Vector3D(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Vector3D(const Vector3D& from);
  Vector3D(Vector3D&& from) noexcept
    : Vector3D() {
    *this = ::std::move(from);
  }

  inline Vector3D& operator=(const Vector3D& from) {
    CopyFrom(from);
    return *this;
  }
  inline Vector3D& operator=(Vector3D&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Vector3D& default_instance() {
    return *internal_default_instance();
  }
  static inline const Vector3D* internal_default_instance() {
    return reinterpret_cast<const Vector3D*>(
               &_Vector3D_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Vector3D& a, Vector3D& b) {
    a.Swap(&b);
  }
  inline void Swap(Vector3D* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Vector3D* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Vector3D* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Vector3D>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Vector3D& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Vector3D& from) {
    Vector3D::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Vector3D* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rov.telemetry.Vector3D";
  }
  protected:
  explicit Vector3D(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
    kZFieldNumber = 3,
  };
  // float x = 1;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 2;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 3;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // @@protoc_insertion_point(class_scope:rov.telemetry.Vector3D)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    float x_;
    float y_;
    float z_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_telemetry_2eproto;
};
// -------------------------------------------------------------------

class SensorData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rov.telemetry.SensorData) */ {
 public:
  inline SensorData() : SensorData(nullptr) {}
  ~SensorData() override;
  explicit PROTOBUF_CONSTEXPR SensorData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SensorData(const SensorData& from);
  SensorData(SensorData&& from) noexcept
    : SensorData() {
    *this = ::std::move(from);
  }

  inline SensorData& operator=(const SensorData& from) {
    CopyFrom(from);
    return *this;
  }
  inline SensorData& operator=(SensorData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SensorData& default_instance() {
    return *internal_default_instance();
  }
  static inline const SensorData* internal_default_instance() {
    return reinterpret_cast<const SensorData*>(
               &_SensorData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(SensorData& a, SensorData& b) {
    a.Swap(&b);
  }
  inline void Swap(SensorData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SensorData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SensorData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SensorData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SensorData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SensorData& from) {
    SensorData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SensorData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rov.telemetry.SensorData";
  }
  protected:
  explicit SensorData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccelerationFieldNumber = 2,
    kAngularVelocityFieldNumber = 3,
    kTimestampUsFieldNumber = 1,
    kDepthFieldNumber = 4,
    kTemperatureFieldNumber = 5,
  };
  // .rov.telemetry.Vector3D acceleration = 2;
  bool has_acceleration() const;
  private:
  bool _internal_has_acceleration() const;
  public:
  void clear_acceleration();
  const ::rov::telemetry::Vector3D& acceleration() const;
  PROTOBUF_NODISCARD ::rov::telemetry::Vector3D* release_acceleration();
  ::rov::telemetry::Vector3D* mutable_acceleration();
  void set_allocated_acceleration(::rov::telemetry::Vector3D* acceleration);
  private:
  const ::rov::telemetry::Vector3D& _internal_acceleration() const;
  ::rov::telemetry::Vector3D* _internal_mutable_acceleration();
  public:
  void unsafe_arena_set_allocated_acceleration(
      ::rov::telemetry::Vector3D* acceleration);
  ::rov::telemetry::Vector3D* unsafe_arena_release_acceleration();

  // .rov.telemetry.Vector3D angular_velocity = 3;
  bool has_angular_velocity() const;
  private:
  bool _internal_has_angular_velocity() const;
  public:
  void clear_angular_velocity();
  const ::rov::telemetry::Vector3D& angular_velocity() const;
  PROTOBUF_NODISCARD ::rov::telemetry::Vector3D* release_angular_velocity();
  ::rov::telemetry::Vector3D* mutable_angular_velocity();
  void set_allocated_angular_velocity(::rov::telemetry::Vector3D* angular_velocity);
  private:
  const ::rov::telemetry::Vector3D& _internal_angular_velocity() const;
  ::rov::telemetry::Vector3D* _internal_mutable_angular_velocity();
  public:
  void unsafe_arena_set_allocated_angular_velocity(
      ::rov::telemetry::Vector3D* angular_velocity);
  ::rov::telemetry::Vector3D* unsafe_arena_release_angular_velocity();

  // uint64 timestamp_us = 1;
  void clear_timestamp_us();
  uint64_t timestamp_us() const;
  void set_timestamp_us(uint64_t value);
  private:
  uint64_t _internal_timestamp_us() const;
  void _internal_set_timestamp_us(uint64_t value);
  public:

  // float depth = 4;
  void clear_depth();
  float depth() const;
  void set_depth(float value);
  private:
  float _internal_depth() const;
  void _internal_set_depth(float value);
  public:

  // float temperature = 5;
  void clear_temperature();
  float temperature() const;
  void set_temperature(float value);
  private:
  float _internal_temperature() const;
  void _internal_set_temperature(float value);
  public:

  // @@protoc_insertion_point(class_scope:rov.telemetry.SensorData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::rov::telemetry::Vector3D* acceleration_;
    ::rov::telemetry::Vector3D* angular_velocity_;
    uint64_t timestamp_us_;
    float depth_;
    float temperature_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_telemetry_2eproto;
};
// -------------------------------------------------------------------

class JoystickCommand final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rov.telemetry.JoystickCommand) */ {
 public:
  inline JoystickCommand() : JoystickCommand(nullptr) {}
  ~JoystickCommand() override;
  explicit PROTOBUF_CONSTEXPR JoystickCommand(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  JoystickCommand(const JoystickCommand& from);
  JoystickCommand(JoystickCommand&& from) noexcept
    : JoystickCommand() {
    *this = ::std::move(from);
  }

  inline JoystickCommand& operator=(const JoystickCommand& from) {
    CopyFrom(from);
    return *this;
  }
  inline JoystickCommand& operator=(JoystickCommand&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const JoystickCommand& default_instance() {
    return *internal_default_instance();
  }
  static inline const JoystickCommand* internal_default_instance() {
    return reinterpret_cast<const JoystickCommand*>(
               &_JoystickCommand_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(JoystickCommand& a, JoystickCommand& b) {
    a.Swap(&b);
  }
  inline void Swap(JoystickCommand* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(JoystickCommand* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  JoystickCommand* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<JoystickCommand>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const JoystickCommand& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const JoystickCommand& from) {
    JoystickCommand::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(JoystickCommand* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rov.telemetry.JoystickCommand";
  }
  protected:
  explicit JoystickCommand(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTimestampUsFieldNumber = 1,
    kForwardFieldNumber = 2,
    kStrafeFieldNumber = 3,
    kVerticalFieldNumber = 4,
    kPitchFieldNumber = 5,
    kRollFieldNumber = 6,
    kYawFieldNumber = 7,
  };
  // uint64 timestamp_us = 1;
  void clear_timestamp_us();
  uint64_t timestamp_us() const;
  void set_timestamp_us(uint64_t value);
  private:
  uint64_t _internal_timestamp_us() const;
  void _internal_set_timestamp_us(uint64_t value);
  public:

  // float forward = 2;
  void clear_forward();
  float forward() const;
  void set_forward(float value);
  private:
  float _internal_forward() const;
  void _internal_set_forward(float value);
  public:

  // float strafe = 3;
  void clear_strafe();
  float strafe() const;
  void set_strafe(float value);
  private:
  float _internal_strafe() const;
  void _internal_set_strafe(float value);
  public:

  // float vertical = 4;
  void clear_vertical();
  float vertical() const;
  void set_vertical(float value);
  private:
  float _internal_vertical() const;
  void _internal_set_vertical(float value);
  public:

  // float pitch = 5;
  void clear_pitch();
  float pitch() const;
  void set_pitch(float value);
  private:
  float _internal_pitch() const;
  void _internal_set_pitch(float value);
  public:

  // float roll = 6;
  void clear_roll();
  float roll() const;
  void set_roll(float value);
  private:
  float _internal_roll() const;
  void _internal_set_roll(float value);
  public:

  // float yaw = 7;
  void clear_yaw();
  float yaw() const;
  void set_yaw(float value);
  private:
  float _internal_yaw() const;
  void _internal_set_yaw(float value);
  public:

  // @@protoc_insertion_point(class_scope:rov.telemetry.JoystickCommand)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    uint64_t timestamp_us_;
    float forward_;
    float strafe_;
    float vertical_;
    float pitch_;
    float roll_;
    float yaw_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_telemetry_2eproto;
};
// -------------------------------------------------------------------

class test final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:rov.telemetry.test) */ {
 public:
  inline test() : test(nullptr) {}
  ~test() override;
  explicit PROTOBUF_CONSTEXPR test(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  test(const test& from);
  test(test&& from) noexcept
    : test() {
    *this = ::std::move(from);
  }

  inline test& operator=(const test& from) {
    CopyFrom(from);
    return *this;
  }
  inline test& operator=(test&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const test& default_instance() {
    return *internal_default_instance();
  }
  static inline const test* internal_default_instance() {
    return reinterpret_cast<const test*>(
               &_test_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(test& a, test& b) {
    a.Swap(&b);
  }
  inline void Swap(test* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(test* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  test* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<test>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const test& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const test& from) {
    test::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(test* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "rov.telemetry.test";
  }
  protected:
  explicit test(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMsgFieldNumber = 1,
  };
  // string msg = 1;
  void clear_msg();
  const std::string& msg() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_msg(ArgT0&& arg0, ArgT... args);
  std::string* mutable_msg();
  PROTOBUF_NODISCARD std::string* release_msg();
  void set_allocated_msg(std::string* msg);
  private:
  const std::string& _internal_msg() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_msg(const std::string& value);
  std::string* _internal_mutable_msg();
  public:

  // @@protoc_insertion_point(class_scope:rov.telemetry.test)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr msg_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_telemetry_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Vector3D

// float x = 1;
inline void Vector3D::clear_x() {
  _impl_.x_ = 0;
}
inline float Vector3D::_internal_x() const {
  return _impl_.x_;
}
inline float Vector3D::x() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.Vector3D.x)
  return _internal_x();
}
inline void Vector3D::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Vector3D::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.Vector3D.x)
}

// float y = 2;
inline void Vector3D::clear_y() {
  _impl_.y_ = 0;
}
inline float Vector3D::_internal_y() const {
  return _impl_.y_;
}
inline float Vector3D::y() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.Vector3D.y)
  return _internal_y();
}
inline void Vector3D::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Vector3D::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.Vector3D.y)
}

// float z = 3;
inline void Vector3D::clear_z() {
  _impl_.z_ = 0;
}
inline float Vector3D::_internal_z() const {
  return _impl_.z_;
}
inline float Vector3D::z() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.Vector3D.z)
  return _internal_z();
}
inline void Vector3D::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Vector3D::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.Vector3D.z)
}

// -------------------------------------------------------------------

// SensorData

// uint64 timestamp_us = 1;
inline void SensorData::clear_timestamp_us() {
  _impl_.timestamp_us_ = uint64_t{0u};
}
inline uint64_t SensorData::_internal_timestamp_us() const {
  return _impl_.timestamp_us_;
}
inline uint64_t SensorData::timestamp_us() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.SensorData.timestamp_us)
  return _internal_timestamp_us();
}
inline void SensorData::_internal_set_timestamp_us(uint64_t value) {
  
  _impl_.timestamp_us_ = value;
}
inline void SensorData::set_timestamp_us(uint64_t value) {
  _internal_set_timestamp_us(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.SensorData.timestamp_us)
}

// .rov.telemetry.Vector3D acceleration = 2;
inline bool SensorData::_internal_has_acceleration() const {
  return this != internal_default_instance() && _impl_.acceleration_ != nullptr;
}
inline bool SensorData::has_acceleration() const {
  return _internal_has_acceleration();
}
inline void SensorData::clear_acceleration() {
  if (GetArenaForAllocation() == nullptr && _impl_.acceleration_ != nullptr) {
    delete _impl_.acceleration_;
  }
  _impl_.acceleration_ = nullptr;
}
inline const ::rov::telemetry::Vector3D& SensorData::_internal_acceleration() const {
  const ::rov::telemetry::Vector3D* p = _impl_.acceleration_;
  return p != nullptr ? *p : reinterpret_cast<const ::rov::telemetry::Vector3D&>(
      ::rov::telemetry::_Vector3D_default_instance_);
}
inline const ::rov::telemetry::Vector3D& SensorData::acceleration() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.SensorData.acceleration)
  return _internal_acceleration();
}
inline void SensorData::unsafe_arena_set_allocated_acceleration(
    ::rov::telemetry::Vector3D* acceleration) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.acceleration_);
  }
  _impl_.acceleration_ = acceleration;
  if (acceleration) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rov.telemetry.SensorData.acceleration)
}
inline ::rov::telemetry::Vector3D* SensorData::release_acceleration() {
  
  ::rov::telemetry::Vector3D* temp = _impl_.acceleration_;
  _impl_.acceleration_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rov::telemetry::Vector3D* SensorData::unsafe_arena_release_acceleration() {
  // @@protoc_insertion_point(field_release:rov.telemetry.SensorData.acceleration)
  
  ::rov::telemetry::Vector3D* temp = _impl_.acceleration_;
  _impl_.acceleration_ = nullptr;
  return temp;
}
inline ::rov::telemetry::Vector3D* SensorData::_internal_mutable_acceleration() {
  
  if (_impl_.acceleration_ == nullptr) {
    auto* p = CreateMaybeMessage<::rov::telemetry::Vector3D>(GetArenaForAllocation());
    _impl_.acceleration_ = p;
  }
  return _impl_.acceleration_;
}
inline ::rov::telemetry::Vector3D* SensorData::mutable_acceleration() {
  ::rov::telemetry::Vector3D* _msg = _internal_mutable_acceleration();
  // @@protoc_insertion_point(field_mutable:rov.telemetry.SensorData.acceleration)
  return _msg;
}
inline void SensorData::set_allocated_acceleration(::rov::telemetry::Vector3D* acceleration) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.acceleration_;
  }
  if (acceleration) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(acceleration);
    if (message_arena != submessage_arena) {
      acceleration = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, acceleration, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.acceleration_ = acceleration;
  // @@protoc_insertion_point(field_set_allocated:rov.telemetry.SensorData.acceleration)
}

// .rov.telemetry.Vector3D angular_velocity = 3;
inline bool SensorData::_internal_has_angular_velocity() const {
  return this != internal_default_instance() && _impl_.angular_velocity_ != nullptr;
}
inline bool SensorData::has_angular_velocity() const {
  return _internal_has_angular_velocity();
}
inline void SensorData::clear_angular_velocity() {
  if (GetArenaForAllocation() == nullptr && _impl_.angular_velocity_ != nullptr) {
    delete _impl_.angular_velocity_;
  }
  _impl_.angular_velocity_ = nullptr;
}
inline const ::rov::telemetry::Vector3D& SensorData::_internal_angular_velocity() const {
  const ::rov::telemetry::Vector3D* p = _impl_.angular_velocity_;
  return p != nullptr ? *p : reinterpret_cast<const ::rov::telemetry::Vector3D&>(
      ::rov::telemetry::_Vector3D_default_instance_);
}
inline const ::rov::telemetry::Vector3D& SensorData::angular_velocity() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.SensorData.angular_velocity)
  return _internal_angular_velocity();
}
inline void SensorData::unsafe_arena_set_allocated_angular_velocity(
    ::rov::telemetry::Vector3D* angular_velocity) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.angular_velocity_);
  }
  _impl_.angular_velocity_ = angular_velocity;
  if (angular_velocity) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:rov.telemetry.SensorData.angular_velocity)
}
inline ::rov::telemetry::Vector3D* SensorData::release_angular_velocity() {
  
  ::rov::telemetry::Vector3D* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::rov::telemetry::Vector3D* SensorData::unsafe_arena_release_angular_velocity() {
  // @@protoc_insertion_point(field_release:rov.telemetry.SensorData.angular_velocity)
  
  ::rov::telemetry::Vector3D* temp = _impl_.angular_velocity_;
  _impl_.angular_velocity_ = nullptr;
  return temp;
}
inline ::rov::telemetry::Vector3D* SensorData::_internal_mutable_angular_velocity() {
  
  if (_impl_.angular_velocity_ == nullptr) {
    auto* p = CreateMaybeMessage<::rov::telemetry::Vector3D>(GetArenaForAllocation());
    _impl_.angular_velocity_ = p;
  }
  return _impl_.angular_velocity_;
}
inline ::rov::telemetry::Vector3D* SensorData::mutable_angular_velocity() {
  ::rov::telemetry::Vector3D* _msg = _internal_mutable_angular_velocity();
  // @@protoc_insertion_point(field_mutable:rov.telemetry.SensorData.angular_velocity)
  return _msg;
}
inline void SensorData::set_allocated_angular_velocity(::rov::telemetry::Vector3D* angular_velocity) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.angular_velocity_;
  }
  if (angular_velocity) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(angular_velocity);
    if (message_arena != submessage_arena) {
      angular_velocity = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, angular_velocity, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.angular_velocity_ = angular_velocity;
  // @@protoc_insertion_point(field_set_allocated:rov.telemetry.SensorData.angular_velocity)
}

// float depth = 4;
inline void SensorData::clear_depth() {
  _impl_.depth_ = 0;
}
inline float SensorData::_internal_depth() const {
  return _impl_.depth_;
}
inline float SensorData::depth() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.SensorData.depth)
  return _internal_depth();
}
inline void SensorData::_internal_set_depth(float value) {
  
  _impl_.depth_ = value;
}
inline void SensorData::set_depth(float value) {
  _internal_set_depth(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.SensorData.depth)
}

// float temperature = 5;
inline void SensorData::clear_temperature() {
  _impl_.temperature_ = 0;
}
inline float SensorData::_internal_temperature() const {
  return _impl_.temperature_;
}
inline float SensorData::temperature() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.SensorData.temperature)
  return _internal_temperature();
}
inline void SensorData::_internal_set_temperature(float value) {
  
  _impl_.temperature_ = value;
}
inline void SensorData::set_temperature(float value) {
  _internal_set_temperature(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.SensorData.temperature)
}

// -------------------------------------------------------------------

// JoystickCommand

// uint64 timestamp_us = 1;
inline void JoystickCommand::clear_timestamp_us() {
  _impl_.timestamp_us_ = uint64_t{0u};
}
inline uint64_t JoystickCommand::_internal_timestamp_us() const {
  return _impl_.timestamp_us_;
}
inline uint64_t JoystickCommand::timestamp_us() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.timestamp_us)
  return _internal_timestamp_us();
}
inline void JoystickCommand::_internal_set_timestamp_us(uint64_t value) {
  
  _impl_.timestamp_us_ = value;
}
inline void JoystickCommand::set_timestamp_us(uint64_t value) {
  _internal_set_timestamp_us(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.timestamp_us)
}

// float forward = 2;
inline void JoystickCommand::clear_forward() {
  _impl_.forward_ = 0;
}
inline float JoystickCommand::_internal_forward() const {
  return _impl_.forward_;
}
inline float JoystickCommand::forward() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.forward)
  return _internal_forward();
}
inline void JoystickCommand::_internal_set_forward(float value) {
  
  _impl_.forward_ = value;
}
inline void JoystickCommand::set_forward(float value) {
  _internal_set_forward(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.forward)
}

// float strafe = 3;
inline void JoystickCommand::clear_strafe() {
  _impl_.strafe_ = 0;
}
inline float JoystickCommand::_internal_strafe() const {
  return _impl_.strafe_;
}
inline float JoystickCommand::strafe() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.strafe)
  return _internal_strafe();
}
inline void JoystickCommand::_internal_set_strafe(float value) {
  
  _impl_.strafe_ = value;
}
inline void JoystickCommand::set_strafe(float value) {
  _internal_set_strafe(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.strafe)
}

// float vertical = 4;
inline void JoystickCommand::clear_vertical() {
  _impl_.vertical_ = 0;
}
inline float JoystickCommand::_internal_vertical() const {
  return _impl_.vertical_;
}
inline float JoystickCommand::vertical() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.vertical)
  return _internal_vertical();
}
inline void JoystickCommand::_internal_set_vertical(float value) {
  
  _impl_.vertical_ = value;
}
inline void JoystickCommand::set_vertical(float value) {
  _internal_set_vertical(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.vertical)
}

// float pitch = 5;
inline void JoystickCommand::clear_pitch() {
  _impl_.pitch_ = 0;
}
inline float JoystickCommand::_internal_pitch() const {
  return _impl_.pitch_;
}
inline float JoystickCommand::pitch() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.pitch)
  return _internal_pitch();
}
inline void JoystickCommand::_internal_set_pitch(float value) {
  
  _impl_.pitch_ = value;
}
inline void JoystickCommand::set_pitch(float value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.pitch)
}

// float roll = 6;
inline void JoystickCommand::clear_roll() {
  _impl_.roll_ = 0;
}
inline float JoystickCommand::_internal_roll() const {
  return _impl_.roll_;
}
inline float JoystickCommand::roll() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.roll)
  return _internal_roll();
}
inline void JoystickCommand::_internal_set_roll(float value) {
  
  _impl_.roll_ = value;
}
inline void JoystickCommand::set_roll(float value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.roll)
}

// float yaw = 7;
inline void JoystickCommand::clear_yaw() {
  _impl_.yaw_ = 0;
}
inline float JoystickCommand::_internal_yaw() const {
  return _impl_.yaw_;
}
inline float JoystickCommand::yaw() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.JoystickCommand.yaw)
  return _internal_yaw();
}
inline void JoystickCommand::_internal_set_yaw(float value) {
  
  _impl_.yaw_ = value;
}
inline void JoystickCommand::set_yaw(float value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:rov.telemetry.JoystickCommand.yaw)
}

// -------------------------------------------------------------------

// test

// string msg = 1;
inline void test::clear_msg() {
  _impl_.msg_.ClearToEmpty();
}
inline const std::string& test::msg() const {
  // @@protoc_insertion_point(field_get:rov.telemetry.test.msg)
  return _internal_msg();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void test::set_msg(ArgT0&& arg0, ArgT... args) {
 
 _impl_.msg_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:rov.telemetry.test.msg)
}
inline std::string* test::mutable_msg() {
  std::string* _s = _internal_mutable_msg();
  // @@protoc_insertion_point(field_mutable:rov.telemetry.test.msg)
  return _s;
}
inline const std::string& test::_internal_msg() const {
  return _impl_.msg_.Get();
}
inline void test::_internal_set_msg(const std::string& value) {
  
  _impl_.msg_.Set(value, GetArenaForAllocation());
}
inline std::string* test::_internal_mutable_msg() {
  
  return _impl_.msg_.Mutable(GetArenaForAllocation());
}
inline std::string* test::release_msg() {
  // @@protoc_insertion_point(field_release:rov.telemetry.test.msg)
  return _impl_.msg_.Release();
}
inline void test::set_allocated_msg(std::string* msg) {
  if (msg != nullptr) {
    
  } else {
    
  }
  _impl_.msg_.SetAllocated(msg, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.msg_.IsDefault()) {
    _impl_.msg_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:rov.telemetry.test.msg)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace telemetry
}  // namespace rov

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_telemetry_2eproto
